### ISSUE TITLE
Asking for some advices on structural data UKBB

### ISSUE THREAD

**Issue by Elise-douard** [brainhack-school2020/hannahkiesow_RiskyBrain#2]
Hey Hannah, 

As you said that your main thesis project is on UKBB, I may have some questions during the following weeks on their derived-structural data and the corrections to add to the models. 
Do you have some references of predilection about that? 

Thanks and see you in dm ;)

**Comment by hannahkiesow** [comment]
Yes! Will write you on slack :P
